"""Message Response Can be null

Revision ID: 48e3c74b9d45
Revises: a1fb27557076
Create Date: 2025-02-17 23:50:19.300138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e3c74b9d45'
down_revision = 'a1fb27557076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
