"""chat on delete cascade

Revision ID: 846a3d2906db
Revises: 48e3c74b9d45
Create Date: 2025-02-22 00:57:58.707215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846a3d2906db'
down_revision = '48e3c74b9d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_chat_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_chat_id_fkey', 'chat', ['chat_id'], ['id'])

    # ### end Alembic commands ###
