"""freq column removed

Revision ID: a8ee23ca214b
Revises: 
Create Date: 2025-03-03 12:57:22.499131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ee23ca214b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
