"""conversational content promt and responseseparated

Revision ID: c013102f429e
Revises: a52c1812d0a1
Create Date: 2025-03-03 11:43:57.648076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c013102f429e'
down_revision = 'a52c1812d0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_context', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('response', sa.Text(), nullable=False))
        batch_op.drop_column('context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_context', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('response')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
